name: .NET CI (Build + Test + Artifact)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore HelloWorld/HelloWorld.csproj

      - name: Build project
        run: dotnet build HelloWorld/HelloWorld.csproj --configuration Release

      - name: Run tests
        run: |
          echo "No tests yet, skipping..." 
          # Add your test project and run 'dotnet test' if available

      - name: Run App
        run: dotnet run --project HelloWorld/HelloWorld.csproj

      - name: Publish artifact
        run: dotnet publish HelloWorld/HelloWorld.csproj --configuration Release --output publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-artifact
          path: HelloWorld/publish/

